version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-axon
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classicmodels
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  node:
    build: .
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: classicmodels
      DB_PORT: 3306
    command: node wait-for-mysql.js

volumes:
  mysql-data:

